serviceAccount:
  create: true
  name: sa-development-pipeline

role:
  bind: true
  name: development-pipeline
  create: true

pvc:
  storageClass: standard
  size: 1Gi

tasks:
  kubernetes:
    createClusterImage: &base_image standard-container:1.0
    createClusterPlaybook: /playbooks/create-cluster.yaml
    getKubeconfigPlaybook: /playbooks/get-kubeconfig.yaml
    validateClusterPlaybook: /playbooks/validate-cluster.yaml
  setup:
    setupConfigImage: *base_image
  git:
    gitPlaybook: /playbooks/git-microflow.yaml
  image:
    buildImage: *base_image
    sidecarServer: docker:19-dind
    insecureRegistry: harbor-core.jarvis.local
    imagePlaybook: /playbooks/images-microflow.yaml
    name: standard-container.yaml
  chart:
    buildChartImage: *base_image
    chartPlaybook: /playbooks/charts-microflow.yaml
  deploymentManifests:
    deploymentManifestsImage: *base_image
    deploymentManifestsPlaybook: /playbooks/deployment-manifests.yaml
  promote:
    promoteImage: *base_image
    promotePlaybook: /playbooks/promote-microflow.yaml
  functional:
    functionalDeployImage: *base_image
    functionalTestImage: *base_image
    functionalPlaybook: /playbooks/functional-microflow.yaml
  cleanup:
    cleanupImage: *base_image
    cleanupPlaybook: /playbooks/cleanup.yaml
