- set_fact:
    _delay: "{{ _delay |default(5) }}"
    _retries: "{{ _retries |default(30) }}"

- name: Check sync status
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  delay: "{{ _delay }}"
  retries: "{{ _retries }}"
