#Validate Kubernetes cluster is accessible.
- set_fact:
    existing_cluster: "{{ use_existing_cluster }}"
- name: Validate kubeconfig
  shell: kubectl --kubeconfig="{{ cluster_kubeconfig_path }}/kubeconfig" get pods -n "{{ namespace }}"
- name: Find existing service accounts
  shell: kubectl --kubeconfig="{{ cluster_kubeconfig_path }}/kubeconfig" get serviceaccounts -n "{{ namespace }}"