apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-flow
data:
  cluster.json: |
    {
     "use_existing_cluster": "true"
    }
  image.json: |
    {
     "build_from_source": true,
     "image_from": "harbor-core.jarvis.local/library/ubuntu:focal",
     "image_name": "udm",
     "project": "udm",
     "repo": "udm",
     "tag": "1.built",
     "image_fullname": "cnf/udm:1.0",
     "path": "images/udm",
     "build": {
        "git_repo": "{{ $.Values.git_repo }}",
        "checkout_loc": "/src/checkout/udm",
        "refspec": "{{ $.Values.refspec }}",
        "version": "refs/changes/*:refs/changes/*"
     }
    }
  chart.json: |
    {
      "chart_name": "udm",
      "project": "udm",
      "repo": "udm",
      "version": "0.1.0",
      "build_from_source": true,
      "path": "charts",
      "build": {
        "git_repo": "{{ $.Values.git_repo }}",
        "checkout_loc": "/src/checkout/airship/charts",
        "refspec": "{{ $.Values.refspec }}",
        "version": "refs/changes/*:refs/changes/*"
      },
      "namespace": "development-pipeline",
      "release_name": "udm",
      "images": {
        "applications": {
          "udm": {
            "tag": "1.0",
            "name": "udm",
            "repo": "udm"
          }
        }
      }
    }
  default.json: |
    {
      "proxy": {
        "http": "",
        "https": "",
        "noproxy": "",
        "enabled": false
      },
     "chart_registry_url": "harbor-core.jarvis.local/chartrepo",
     "chart_repository": "jarvis-harbor",
     "docker_registry": "harbor-core.jarvis.local",
     "harbor_secret_mounted_path": "/workspace/helm-creds"
    }
  cleanup.json: |
    {
     "remove_artifacts": "true"
    }
