loki:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: loki.jarvis.local
        paths: ["/"]
    public: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-XSS-Protection: 1; mode=block";
      nginx.ingress.kubernetes.io/rewrite-target: /

promtail:
  enabled: true

grafana:
  enabled: false
