#Validate Kubernetes cluster is accessible.
- set_fact:
    existing_cluster: "{{ use_existing_cluster }}"
- name: Get kubeconfig
  shell: echo "Retrieve kubeconfig from mounted secret"
  when: existing_cluster
- name: Validate kubeconfig
  shell: kubectl --kubeconfig="{{ cluster_kubeconfig_path }}/kubeconfig" get pods -n development-pipeline
- name: Find existing service accounts
  shell: kubectl --kubeconfig="{{ cluster_kubeconfig_path }}/kubeconfig" get serviceaccounts -n development-pipeline