{{- define "Secret-netrc" -}}
{{- $HARBOR_URL := $.Values.params.harbor.host -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "helpers.labels.fullname" . }}-netrc
data:
  harbor-netrc: {{ b64enc ( printf "machine %s login %s password %s" $HARBOR_URL $.Values.config.test.ldap_username $.Values.config.test.ldap_password ) }}
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Secret-netrc" ) }}
