build_from_source: true
project: "test"
repo: "scratch"
tag: "1.built"
build:
  git_repo: "https://review.opendev.org/airship/charts"
  checkout_loc: "/src/checkout/scratch"
  refspec: "refs/changes/41/770141/7"
  version: "refs/changes/*:refs/changes/*"
makefile:
  path: "tools/images"
  target: "build"
  file: "Makefile"
  image_name: "scratch"
  image_base: "scratch"