apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task gathers logs and cleans up the environment
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: cleanup
      image: {{ $.Values.tasks.cleanup.cleanupImage }}
      volumeMounts:
        - mountPath: $(workspaces.development_pipeline_data.path)/config
          name:  kubeconfig
      script: |
        #!/bin/sh
        ansible-playbook -vvv "{{ $.Values.tasks.cleanup.cleanupPlaybook }}" -i hosts \
        -e @"$(workspaces.development_pipeline_data.path)/default.json" \
        -e 'loop_chart_source="$(workspaces.development_pipeline_data.path)/chart.json"' \
        -e 'loop_image_source="$(workspaces.development_pipeline_data.path)/image.json"' \
        -e @"$(workspaces.development_pipeline_data.path)/cluster.json"
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig-secret
