apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-cluster-config
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task sets configurations that will be used as overrides to the Ansible tasks.
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: setup-cluster-config
      image: {{ $.Values.tasks.setup.setupConfigImage }}
      script: |
        ls -ltr /opt/
        /jarvis/setup_cluster_config.sh
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-image-config
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task sets configurations that will be used as overrides to the Ansible tasks.
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: setup-image-config
      image: {{ $.Values.tasks.setup.setupConfigImage }}
      script: |
        /jarvis/setup_image_config.sh $(context.taskRun.uid)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-chart-config
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task sets configurations that will be used as overrides to the Ansible tasks.
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: setup-chart-config
      image: {{ $.Values.tasks.setup.setupConfigImage }}
      script: |
        /jarvis/setup_chart_config.sh $(context.taskRun.uid)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-cleanup-config
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task sets configurations that will be used as overrides to the Ansible tasks.
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: setup-cleanup-config
      image: {{ $.Values.tasks.setup.setupConfigImage }}
      script: |
        /jarvis/setup_cleanup_config.sh $(context.taskRun.uid)
