apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deployment-manifests
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task will do any validation of manifests required to deploy the CNF
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: example-validation-step
      image: {{ $.Values.tasks.deploymentManifests.deploymentManifestsImage }}
      script: |
        /jarvis/deployment_manifests.sh