apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: {{ $.Release.Namespace }}
spec:
  description: >-
    This task gathers logs and cleans up the environment
  workspaces:
    - name: k8s_cluster_data
    - name: development_pipeline_data
  steps:
    - name: cleanup
      image: {{ $.Values.tasks.cleanup.cleanupImage }}
      volumeMounts:
        - mountPath: $(workspaces.development_pipeline_data.path)/config
          name:  kubeconfig
      script: |
        /jarvis/cleanup.sh
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig-secret
